#ifndef __WERKZEUGKISTE_VERSION_H__
#define __WERKZEUGKISTE_VERSION_H__

#define WERKZEUGKISTE_VERSION  "0.1.0"
#define WERKZEUGKISTE_VERSION_MAJOR "0"
#define WERKZEUGKISTE_VERSION_MINOR "1"
#define WERKZEUGKISTE_VERSION_PATCH "0"

#endif  // __WERKZEUGKISTE_VERSION_H__

